alias lsa='ls -la'
alias cl='clear'
alias vim='nvim'
alias vi='vi'

alias gs='git status'
alias gl='git log'
alias glp='git log -p'
alias gd='git diff'
alias gds='git diff --staged'
alias gb='git branch'
alias gc='git commit'
